<?php
    /*
     * GOOGLE ANALYTICS
     */
if( (
        !estActifOuPasDoNotTrackHeader()
        &&
        (isset($_COOKIE['CookieApp_CA']) && $_COOKIE['CookieApp_CA'] == 1)
        &&
        (isset($_COOKIE['CookieApp_CA_Ganalytics']) && $_COOKIE['CookieApp_CA_Ganalytics'] == 1)
    )
    ||
    (
    !isset($_COOKIE['CookieApp_CO_LeCookie'])
    )
) {

    echo <<<EOD

	<!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-43709598-7"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-43709598-7');
    </script>

EOD
    ;
}

/*
 * PIWIKS MATOMO ANALYTICS
 */
    if( !estActifOuPasDoNotTrackHeader()
        &&
        (isset($_COOKIE['CookieApp_CA']) && $_COOKIE['CookieApp_CA'] == 1)
        &&
        (isset($_COOKIE['CookieApp_CA_Piwik']) && $_COOKIE['CookieApp_CA_Piwik'] == 1)
    ) {

        echo <<<EOD
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo.infoartsmedia.org/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
EOD
        ;
    }

/*
 * SEGMENT APP ANALYTICS
 */
if( !estActifOuPasDoNotTrackHeader()
    &&
    (isset($_COOKIE['CookieApp_CA']) && $_COOKIE['CookieApp_CA'] == 1)
    &&
    (isset($_COOKIE['CookieApp_CA_SegmentApp']) && $_COOKIE['CookieApp_CA_SegmentApp'] == 1)
){

    echo <<<EOD
	
	<!-- Segment _App -->
	<script>
        !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
        analytics.load("FyeK0FUxRMyX8pCBlvyIsqP8UQpsZZ9w");
        analytics.page();
        }}();
    </script>
	<!-- End Segment _App -->

EOD;

}

