<?php
PositionneJS();

function PositionneJS(){

    /*
     * DANGER:
     *  A n'utiliser qu'en cas de debugging de CSS
     * Rend tout animé et très gourmand en ressources
     * 
     * echo "<script type='text/javascript' src='/scriptJS/live.js'></script>";
     */

	/*
     * GOODIES :
	 *   Javascript pour les chutes de neige de Noël
     */
	 
    /*
	
    echo <<<EOD
	
	<script type='text/javascript' src='/scriptJS/BD_snow.js'></script>    	
	<script type="text/javascript">
	BD_snow.config= {
	     graphic: 'http://besancon25.fr/images/NouvelAn/etoile.png' 
	    ,amplitude: 20 
	    ,interval: 6 
	    ,speed: 50 
	    ,snowontop: false 
	}
	</script>

EOD;

	*/
	
	/******		Old Mimines Scripts			******/

    echo "\n" . "<script src='/scriptJS/lib/jquery.3.4.1.min.js'></script>";

    echo "\n" . "<script type='text/javascript' src='/scriptJS/cookie.js'></script>";
    echo "\n" . "<script type='text/javascript' src='/scriptJS/afficherCacherDIV.js'></script>";

    echo "\n" . "<script type='text/javascript' src='/scriptJS/effetsMonospaceMachine.js'></script>";
    echo "\n" . "<script type='text/javascript' src='/scriptJS/fonctionsSurvol-LOGOS.js'></script>";

    echo "\n" . "<script type='text/javascript' src='/scriptJS/ajax.js'></script>";
	
	echo "\n" . "<script type='text/javascript' src='/scriptJS/changerCSS.js'></script>";  
    echo "\n" . "<script type='text/javascript' src='/scriptJS/classList.js'></script>";

    echo "\n" . "<script type='text/javascript' src='/scriptJS/Boutons-beerware.js'></script>";

	/******		Relicats			******/
	
    //echo "\n" . "<script type='text/javascript' src='/scriptJS/bouton-bascule/oneAccountBouton.js'></script>";
    //echo "\n" . "<script type='text/javascript' src='/scriptJS/horloge.js'></script>";
	
	/******		FIN Relicats		******/
    
	//POLO Javascript For Alerts and Caroussel
	if(ACTIVATE_UGLY_CSS_STYLE == false){
		
		echo <<<EOD
            <!-- POLO Minimal Template -->
            <script type='text/javascript' src="/scriptJS/assets/js/jquery.js"></script>
            <script type='text/javascript' src="/scriptJS/assets/js/plugins.js"></script>
            <!--POLO Template functions-->
            <script type='text/javascript' src="/scriptJS/assets/js/functions.js"></script>
EOD;

    }
    //Script JS (2006) pour créer des fenetres modales - modifié en 2015
    echo "\n" . "<script type='text/javascript' src='/scriptJS/pageDim.js'></script>";
    echo "\n" . "<script type='text/javascript' src='/scriptJS/subModal-1.6/common.js'></script>";
    echo "\n" . "<script type='text/javascript' src='/scriptJS/subModal-1.6/subModal.js'></script>";

    $version = recuperationCookieVersionInterface();

	if($version == 2) {
        echo "\n" . "<script type='text/javascript' src='/scriptJS/animation-interface-version2.js'></script>";
    }
    if($version !== 4) {
        echo "\n" . "<script type='text/javascript' src='/scriptJS/mobile-menu.js'></script>";
    }
	if($version == 4) {
        echo <<<EOD
		
            <script type='text/javascript' src='/scriptJS/animation-interface-version2.js'></script>
			<!--Rotating Cube functions-->	
            <script type='text/javascript' src="/scriptJS/v4/js/b25-rotating-cube.js"></script>
            <script type='text/javascript' src="/scriptJS/v4/js/b25-reading-connect.js"></script>
			<!--Slider Lecture functions-->	
			<script type='text/javascript'>
				function calculPourcentageHauteur() {
					var hauteurDocument = $(document).height(); // Hauteur du document complet
					var hauteurFenetre = $(window).height(); // Hauteur de la fenêtre courante (viewport)
					var position = $(window).scrollTop(); // Position haute au moment du scroll
					var positionDernierEcran = hauteurDocument - hauteurFenetre; // Position haute du dernier écran visible
					var ratioHauteur = position / positionDernierEcran; // Ratio de la hauteur
					var pourcentageHauteur = Math.floor(ratioHauteur * 100); // Pourcentage de la hauteur

					// Affichage de l'évolution du pourcentage de la hauteur dans la console (optionnel)
					console.log("Pourcentage de la hauteur parcourue : " + pourcentageHauteur + "%");

					return pourcentageHauteur;
				}

				// Barre de défilement horizontale en fonction du scroll
				function barreDefilement() {
					var cible = $("#barre-lecture .progression");
					cible.css({
						"width": calculPourcentageHauteur()+"%"
					});
				}


				// Chargement des fonctions lors du chargement et du scroll
				$(window).on("load scroll", function() {
					barreDefilement(); // Barre-lecture
				});
			</script>
			
EOD;

    }

    //echo "\n" . "<script>window.jQuery || document.write('<script src=\'//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\'><\/script>')</script>";
    //echo "\n" . "<script>window.jQuery || document.write('<script src=\'\/scriptJS/lib/jquery.3.4.1.min.js\'><\/script>')</script>";


    $urlAJAXFeedBack = link_rewrite('postCourrielSignalement',true,'AJAX');
    $urlFeedBack = link_rewrite('traitementSignalementCourriel',true);


	// Javascript For Feedback
    echo "\n" . "<script src='/scriptJS/feedback.js-master/examples/js/jquery.js'></script>";
    echo <<<EOD
<script src="/scriptJS/feedback.js-master/examples/js/feedback.js"></script>
    
    <script type="text/javascript">
      $(document).ready(function() {
        var api = Feedback({
            h2cPath:'/scriptJS/feedback.js-master/examples/js/html2canvas-1.0.0-rc.js',
            appendTo: null, // don't add feedback button to page
            url: '$urlFeedBack',
            adapter: new window.Feedback.REDIRECT( '$urlFeedBack','${_SERVER['REMOTE_ADDR']}' ),
            //url: '$urlAJAXFeedBack',
            //adapter: new window.Feedback.XHR( '$urlAJAXFeedBack','${_SERVER['REMOTE_ADDR']}' ),
            ip: '{$_SERVER['REMOTE_ADDR']}',
        });
        
        // instead, let's open when we click
       document.getElementById('signalement').addEventListener('click',function(){
            api.open();
        });
        
      });          
    </script>
EOD;


// Javascript For VEGAS ANIMATION SLIDER
if(VEGAS_SLIDER && $version !== 1) {
    echo <<<'EOD'
        <!-- vegas main js -->
        <script src="/scriptJS/vegas/vegas.js"></script>
        <script src="/scriptJS/b25-vegas-slideshow.js"></script>
EOD;
}

	// ALL Other Javascript For Programming


	
    return;
}
