<?php


if (!estActifOuPasDoNotTrackHeader()
    &&
    (isset($_COOKIE['CookieApp_CA']) && $_COOKIE['CookieApp_CA'] == 1)
    &&
    (isset($_COOKIE['CookieApp_CA_Gadverts']) && $_COOKIE['CookieApp_CA_Gadverts'] == 1)
) {
    if(isset($_SESSION['nbr_connection'])){
        if($_SESSION['nbr_connection'] < 6 && $_SESSION['nbr_connection']%2 == 0){
            $echo_pub = true;
        }else if($_SESSION['nbr_connection']>6 && $_SESSION['nbr_connection']< 25 && $_SESSION['nbr_connection']%5 == 0){
            $echo_pub =  true;
        }else{
            $echo_pub = false;
        }

        if($echo_pub) {



        }
    }
}
