<?php
if( !estActifOuPasDoNotTrackHeader()) {

    if((isset($_COOKIE['CookieApp_CT']) && $_COOKIE['CookieApp_CT'] == 1)
        &&
        (isset($_COOKIE['CookieApp_CT_Google']) && $_COOKIE['CookieApp_CT_Google'] == 1)
    ){
        echo "<span style='position:relative; top:7px; left: 25px'><g:plusone size='medium' data-annotation='inline'></g:plusone>"
            ."<script type='text/javascript' src='https://apis.google.com/js/plusone.js'>{lang: 'fr'}</script></span>";

    }
    if((isset($_COOKIE['CookieApp_CT']) && $_COOKIE['CookieApp_CT'] == 1)
        &&
        (isset($_COOKIE['CookieApp_CT_Twitter']) && $_COOKIE['CookieApp_CT_Twitter'] == 1)
    ){
        echo "<span style='position:relative; top:2px; left: 100px'><a href='http://twitter.com/share' class='twitter-share-button' data-via='acksop'>Tweet</a></span>"
            ."<script type='text/javascript' src='http://platform.twitter.com/widgets.js'></script>";

    }
    if((isset($_COOKIE['CookieApp_CT']) && $_COOKIE['CookieApp_CT'] == 1)
        &&
        (isset($_COOKIE['CookieApp_CT_LinkedIn']) && $_COOKIE['CookieApp_CT_LinkedIn'] == 1)
    ){
        echo "<script type='text/javascript' src='http://platform.linkedin.com/in.js'></script>"
            ."<span style='position:relative; top:-3px; left: 125px'><script type='in/share' data-counter='right'></script></span>";

    }
    if((isset($_COOKIE['CookieApp_CT']) && $_COOKIE['CookieApp_CT'] == 1)
        &&
        (isset($_COOKIE['CookieApp_CT_Facebook']) && $_COOKIE['CookieApp_CT_Facebook'] == 1)
    ){
        echo "<div id=\"fb-root\"></div><script>(function(d, s, id) {  var js, fjs = d.getElementsByTagName(s)[0];  if (d.getElementById(id)) return;  js = d.createElement(s); js.id = id;  js.src = 'https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v3.2';  fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script>"
            ."<span style='position:relative; top:-28px; left: 200px' class=\"fb-like\" data-href=\"http://besancon25.fr\" data-layout=\"button\" data-action=\"like\" data-size=\"small\" data-show-faces=\"false\" data-share=\"false\"></span>";
    }
}