<?php

require dirname(__FILE__) . '/HTML5-structure/en-tete/meta_balises.phtml';
require dirname(__FILE__) . '/HTML5-structure/en-tete/ecmascript_header.phtml';
require dirname(__FILE__) . '/HTML5-structure/en-tete/entertainement_adsense.phtml';
require dirname(__FILE__) . '/HTML5-structure/en-tete/tagmanager_google.phtml';
require dirname(__FILE__) . '/HTML5-structure/en-tete/analytics_neocamino.phtml';
require dirname(__FILE__) . '/HTML5-structure/en-tete/pixel_facebook.phtml';
require dirname(__FILE__) . '/HTML5-structure/en-tete/css_styles.phtml';