<?php
echo <<<EOD

<title>$header_title</title>
	<!-- ------------------------------------------------------------------------------------------------------------------------------------ -->
	<!--						BALISES DE META-RECHERCHES								-->
	
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
	<META CHARSET="UTF-8" />
	<META HTTP-EQUIV="X-UA-Compatible" CONTENT="IE=edge,chrome=1">
	<META NAME="viewport" CONTENT="width=device-width, initial-scale=1.0">

<!-- 																				 -->

    <meta property="og:title" content="$header_title" />
    <meta property="og:type" content="Plate-forme Web" />
    <meta property="og:url" content="$header_identifier_url" />
    <meta property="og:image" content="https://besancon25.fr/images/Cube/logo_FR.png" />

	<!-- 																				 -->
	
	<META NAME="Category" CONTENT="Plate-forme">
	<META NAME="Publisher" CONTENT="INFO[ARTS]MEDIA">
	<META NAME="Copyright" CONTENT=" - 2010 - Info[ARTS]Media">
	<META NAME="Expires" CONTENT="Never Maybe!">
	<META NAME="Distribution" CONTENT="Global">
	<META NAME="Description" lang='fr' CONTENT="$header_description">
	<META NAME='Identifier-URL' CONTENT="$header_identifier_url">

    <meta name="Keywords" content="$header_keywords">
	<META NAME='Keywords' lang='fr' CONTENT="$header_keywords">

	<META NAME="Author" CONTENT="$header_author">
	<META NAME="Reply-to" CONTENT="contact@besancon25.info">
	<META NAME="Date-Creation-yyyymmdd" CONTENT="20090317">
	<META NAME="Date-Revision-yyyymmdd" CONTENT="20100712">
	<META NAME="Revisit-After" CONTENT="30 days">
	<META NAME="Robots" CONTENT="index">
	<META NAME="GOOGLEBOT" CONTENT="NOARCHIVE">
	
	
	<meta property="fb:admins" content="1245323132"/>
	
	<!--
	
	<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
	<META HTTP-EQUIV="EXPIRES" CONTENT="now">
	<META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
																		-->
	<!-- ------------------------------------------------------------------------------------------------------------------------------------ -->
	<!--																				-->
	<META HTTP-EQUIV="Content-Language" CONTENT="fr">
	<META HTTP-EQUIV="Refresh" CONTENT="NO">

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

	<link rel="alternate" type="application/rss+xml" href="fluxRSS.php?flux=RSS" title="Flux RSS du (B25) - La plate-forme des Artistes,Artisans,Groupes et Associations">
	<link rel="alternate" type="application/rss+xml" href="fluxRSS.php?flux=ATOM" title="Flux ATOM du (B25) - La plate-forme des Artistes,Artisans,Groupes et Associations">
	<!--																				-->
	<!-- ------------------------------------------------------------------------------------------------------------------------------------ -->

EOD;
